# OpenAI Embeddings Configuration
provider: openai
model_name: text-embedding-3-small  # Updated to latest model
display_name: OpenAI Text Embedding 3 Small
enabled: true

# Model specifications
dimensions: 1536
max_tokens: 8191
normalization: true

# API configuration
api_config:
  base_url: https://api.openai.com/v1
  timeout: 30
  max_retries: 3
  retry_delay: 1

# Batch processing
batch_config:
  max_batch_size: 100
  max_concurrent_requests: 10

# Cost information
cost:
  currency: USD
  per_1k_tokens: 0.00002  # Updated pricing for text-embedding-3-small

# Supported tasks
supported_tasks:
  - similarity
  - retrieval
  - clustering
  - classification
